# docker-compose.yml
version: "3.7"
services:
  db:
    image: mysql
    build: ./sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: olio1
      MYSQL_USER: olio1admin
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - "3306"
    security_opt:
      - seccomp:unconfined

  backend:
    build: ./server
    hostname: backend
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080:8080
    environment:
      DEFAULT_DATABASE_URL: jdbc:mysql://localhost:3306/olio1
      MYSQL_USER: olio1admin
      MYSQL_PASSWORD: /run/secrets/db_password
      BACKEND_ADDRESS: 0.0.0.0
      BACKEND_PORT: 8080
    secrets:
      - db_password

secrets:
  db_password:
    file: ./db_password.txt
  db_root_password:
    file: ./db_root_password.txt

volumes:
  db_data:
