# docker-compose.yml
version: "3.7"
services:
  db:
    image: mysql
    build: ./sql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: olio1
      MYSQL_USER: olio1admin
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    volumes:
      - db_data:/var/lib/mysql
    security_opt:
      - seccomp:unconfined

  backend:
    build: ./server
    hostname: backend
    depends_on:
      - db
    links:
      - db
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: jdbc:mysql://db:3306/olio1
      MYSQL_USER: olio1admin
      MYSQL_PASSWORD: /run/secrets/db_password
      HOST: 0.0.0.0
      PORT: 8080
    secrets:
      - db_password

secrets:
  db_password:
    file: ./db_password.txt
  db_root_password:
    file: ./db_root_password.txt

volumes:
  db_data:
